FashionShop/FashionShop/FashionShop/ViewModels/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FashionShop.ViewModels
{
    public class CartViewModel
    {
        public List<CartItem> CartItems { get; set; }

        public CartTotal CartTotal { get; set; }

        public CartViewModel()
        {
            CartItems = new List<CartItem>();
            CartTotal = new CartTotal();
        }
        
    }

   

}

FashionShop/FashionShop/FashionShop/Controllers/CartController.cs
using System.Web.Mvc;
using DataAccess;
using FashionShop.Services;

namespace FashionShop.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;

        public CartController( )
        {
            _cartService = new CartService(new FashionShopEntities());
        }
        // GET: Cart
        public ActionResult Index()
        {
            var cart = _cartService.GetCurrentCart();

            return View(cart);
        }

        [HttpPost]
        public JsonResult AddToCart(string variantCode, int quantity)
        {
            var cartTotal = _cartService.AddToCart(variantCode, quantity);

            return Json(cartTotal, JsonRequestBehavior.AllowGet);
        }
        
    }
}

FashionShop/FashionShop/FashionShop/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataAccess;
using FashionShop.Enumerations;
using FashionShop.Exceptions;
using FashionShop.Services;
using FashionShop.ViewModels;

namespace FashionShop.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly FashionShopEntities _dbContext;
        private readonly ICartService _cartService;

        public CheckoutController()
        {
            _dbContext = new FashionShopEntities();
            _cartService = new CartService(_dbContext);
                
        }
        // GET: Checkout
        public ActionResult Index()
        {
            var viewModel = CreateCheckoutViewModel();
            

            return View(viewModel);
        }

        private CheckoutViewModel CreateCheckoutViewModel()
        {
            //Todo:
            //Get ShippingInformation if logged  ( default ShippingInformation = address of customer)
            //Get Payment method
            var paymentMethodViewModels = _dbContext.PaymentMethods.Select(x => new PaymentMethodViewModel()
            {
                PaymentMethodId = x.PaymentMethodId,
                PaymentMethodName = x.PaymentMethodName,
                Description = x.Description
            }).ToList();

            var model = new CheckoutViewModel()
            {
                Cart = _cartService.GetCurrentCart(),
                PaymentMethods = paymentMethodViewModels,
                ShippingInformation = new ShippingInformationViewModel()
            };

            return model;
        }


        [HttpPost]
        public ActionResult Purchase(ShippingInformationViewModel shippingInformation)
        {
            var checkoutViewModel = CreateCheckoutViewModel();
            checkoutViewModel.ShippingInformation = shippingInformation;

            if (ModelState.IsValid)
            {
                var cart = checkoutViewModel.Cart;

                if (cart.CartItems.Count == 0)
                {
                    ModelState.AddModelError("PurchaseError", "There is empty cart");

                    return View("Index", checkoutViewModel);
                }
                
                try
                {
                    var orderId = PlaceOrder(shippingInformation, cart);
                }
                catch (OutOfStockException ex)
                {
                    ModelState.AddModelError("PurchaseError", ex.Message);

                   return View("Index", checkoutViewModel);
                }
                
                //clear cart
                _cartService.ClearCurrentCart();
               
                return RedirectToAction("Index", "OrderConfirmation"); //orderId

            }
            return View("Index", checkoutViewModel);
        }

        private Guid PlaceOrder(ShippingInformationViewModel shippingInformation, CartViewModel cart)
        {
            //check quantity of cart items in store
            foreach (var cartItem in cart.CartItems)
            {
                var variant = _dbContext.ProductVariants.FirstOrDefault(x => x.ProductVariantId == cartItem.ProductVariantId);
                if (variant == null || variant.Quantity < cartItem.Quantity)
                {
                    throw new OutOfStockException($"Het san pham {cartItem.ProductName} {cartItem.Size}");
                }

                variant.Quantity = variant.Quantity - cartItem.Quantity;
                variant.ModifiedDate = DateTime.Now;
                variant.ModifiedBy = shippingInformation.EmailAddress;
            }

            var order = new Order
            {
                OrderId = Guid.NewGuid() ,
                FullName = shippingInformation.FullName,
                EmailAdress = shippingInformation.EmailAddress,
                Phone = shippingInformation.Phone,
                LineAddress = shippingInformation.LineAddress,
                District = shippingInformation.District,
                City = shippingInformation.City,
                Note = shippingInformation.Note,
                PaymentMethodId = shippingInformation.PaymentMethodId,
                Amount = cart.CartTotal.TotalMoney,
                AmountPaint = 0,
                OrderStatusId = (int) OrderStatusEnum.New,
                CreatedDate = DateTime.Now,
                CreateBy = shippingInformation.EmailAddress,
                ModifiedDate = DateTime.Now,
                ModifiedBy = shippingInformation.EmailAddress
            };

            var orderDetails = new List<OrderDetail>();

            foreach (var cartItem in cart.CartItems)
            {
                var orderDetail = new OrderDetail
                {
                    OrderDetailId = Guid.NewGuid(),
                    OrderId = order.OrderId,
                    Quantity = cartItem.Quantity,
                    UnitPrice = cartItem.Price,
                    ProductVariantId = cartItem.ProductVariantId,
                    CreatedDate = DateTime.Now,
                    CreatedBy = shippingInformation.EmailAddress,
                    ModifiedDate = DateTime.Now,
                    ModifiedBy = shippingInformation.EmailAddress
                };

                orderDetails.Add(orderDetail);
            }

            _dbContext.Orders.Add(order);
            _dbContext.OrderDetails.AddRange(orderDetails);

            _dbContext.SaveChanges();

            return order.OrderId;
        }
    }
}

FashionShop/FashionShop/FashionShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using FashionShop.ViewModels;

namespace FashionShop.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index(string productType, string keyword)
        {
            var model = new ProductListViewModel
            {
                ProductType = productType,
                Keyword = keyword,
                ProductItems = GetProducts(productType,keyword)
            };
            ViewBag.Keyword = keyword;
            ViewBag.ProductType = productType;
            return View(model);
        }
        
      

        private List<ProductItem> GetProducts(string productType, string keyword)
        {
            using (var dbContext = new FashionShopEntities())
            {
                var query = dbContext.Products.AsQueryable();
                if(!string.IsNullOrEmpty(productType))
                {
                    query = query.Where(x => x.ProductType.Name.Equals(productType));
                }

                if (!string.IsNullOrEmpty(keyword))
                {
                    query = query.Where(x => x.Name.Contains(keyword));
                }

                var productItems = query.Select(x => new ProductItem()
                {
                    
                    Name = x.Name,
                    Price = x.Price,
                    ImageSrc = x.Image,
                    Code = x.Code
                }).ToList();

                foreach (var item in productItems)
                {
                    item.DetailLink = BuildDetailLink(item.Code);
                }

                return productItems;
            }

        }

        private List<ProductItem> SearchProducts(string keyword)
        {
            using (var dbContext = new FashionShopEntities())
            {
                var productItems = dbContext.Products.Where(x => x.Name.Contains(keyword)).Select(x => new ProductItem()
                {

                    Name = x.Name,
                    Price = x.Price,
                    ImageSrc = x.Image,
                    Code = x.Code
                }).ToList();

                foreach (var item in productItems)
                {
                    item.DetailLink = BuildDetailLink(item.Code);
                }
                
                return productItems;
            }

        }

        private string BuildDetailLink(string code)
        {
            return $"/ProductDetail?productCode={code}";
        }

    }
}

FashionShop/FashionShop/FashionShop/Views/Cart/Index.cshtml
@model FashionShop.ViewModels.CartViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<div class="container pr-detail" style=" border-bottom: solid; margin-bottom: 50px;">
    <img src="/Content/img/img1.jpg" width="1170" height="600" />
</div>

<div class="container" id="shopping-cart">
    <div class="row no-gutters">
        <div class="col-md-8 col-sm-8 col-xs-12 border-right">
            <div class="text-center">
                <p class="cart-title" style="font-weight: bold; margin-bottom: 20px;">YOUR SHOPPING CART</p>
            </div>
            <table class="table table-responsive order-detail">
                <thead>
                <tr>
                    <th class="text-center">Image</th>
                    <th class="text-center">Product Name</th>
                    <th class="text-center">Color</th>
                    <th class="text-center">Unit Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Total</th>
                    <th class="text-center">Remove</th>
                </tr>
                </thead>
                <tbody class="text-center">
                @foreach (var item in Model.CartItems) { 
                <tr>
                        <td><img src="@item.ImageSrc" alt="" class="product-thumbnail"></td>
                        <td> <p>@item.ProductName</p></td>
                        <td> <p > @item.Color</p></td>
                        <td class="unit-price"> <p>@item.Price   </p></td>
                        <td> @item.Quantity</td>
                        <td > <p>@item.Money </p></td>
                        <td> <p><i class="fa fa-remove btn-sm"></i> </p></td>
                        
         
                   
                </tr>
                }
                </tbody>
            </table>

        </div>
        <div class="col-md-4 col-sm-4 col-xs-12" id="cart-summary-container">
            <table class="table table-responsive" id="cart-summary">
                <thead>
                <tr>
                    <th class="text-center" colspan="2">SUMMARY</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Total quantity</td>
                    <td class="text-right"> @Model.CartTotal.TotalQuantity</td>
                </tr>
                <tr>
                    <td>Total money</td>
                    <td class="text-right">@Model.CartTotal.TotalMoney </td>
                </tr>
                </tbody>
            </table>
          
            <div class="button-group">
                <div>
                    <div style="border: 0px solid #dddddd  ; display: inline-block; background: #dddddd;padding-bottom: 7px;padding-top: 7px;color: black">
                        <a href= @Url.Action("Index", "Products", new { producttype = "Men" })>CONTINUE SHOPPING</a>
                       
@*                        @Html.ActionLink("Continue shopping", "Index", "Products", new { producttype = "Men" }, null)*@
                    </div>
                   
                    <div style="border: 0px solid #dddddd  ; display: inline-block; background: #dddddd;padding-bottom: 7px;padding-top: 7px;color: black">
                        <a href= @Url.Action("Index", "Checkout")>CHECKOUT</a>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

<script>
        $(function(){
            $("#cart-checkout").click(function() {
                toastr["success"]("Added successfully!", "Succseffully");
            });
         });
</script>