FashionShop/FashionShop/FashionShop/Areas/Admin/Controllers/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;

namespace FashionShop.Areas.Admin.Controllers
{
    public class ProductManagerController : Controller
    {
        private readonly FashionShopEntities _dbContext;

        public ProductManagerController()
        {
            _dbContext= new FashionShopEntities();
        }
        public ProductManagerController(FashionShopEntities dbContext)
        {
            _dbContext = dbContext;
        }
        // GET: Admin/ProductManager
        public ActionResult Index()
        {
            return View(_dbContext.Products.ToList());
        }

   
        public ActionResult Sizes()
        {
            return View(_dbContext.Sizes.ToList());

        }
        public ActionResult Color()
        {
            return View(_dbContext.Colors.ToList());

        }
        public ActionResult ProductTypes()
        {
      
            return View(_dbContext.ProductTypes.ToList());

        }
        public ActionResult Create()
        {
            //SelectList
            ViewBag.ProductTypes = _dbContext.ProductTypes.ToList();

            return View();
        }


        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                    _dbContext.Products.Add(product);
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index");
                
            }
            return View(product);
        }
        public ActionResult Edit(int id)
        {
            return View(_dbContext.Products.Find(id));
        }
        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Entry(product).State = EntityState.Modified;
                _dbContext.SaveChanges();
                return RedirectToAction("Index", new { id = product.ProductId });
            }
            return View(product);
        }
        public ActionResult Delete(int id = 0)
        {
            Product product = _dbContext.Products.Single(r => r.ProductId == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var product = _dbContext.Products.Single(r => r.ProductId == id);
            _dbContext.Products.Remove(product);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

FashionShop/FashionShop/FashionShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dashboard", "Index", "Home", new { area = "Admin" }, new { @class = "navbar-brand" }) 
                @Html.ActionLink("Product", "Index", "ProductManager", new { area = "Admin" }, new { @class = "navbar-brand" }) 

            </div>
            
            <div class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Catagory  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                      
                    <li class="sub-item"><a href=@Url.Action("ProductTypes","ProductManager", new { area = "Admin" })>Product Type</a></li>
                    <li class="sub-item"><a href=@Url.Action("Color","ProductManager",new { area ="Admin"})> Color</a></li>
                    <li class="sub-item"><a href=@Url.Action("Sizes","ProductManager", new { area = "Admin" })>Size</a></li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>